version: 2.1

jobs:
  build:
    docker:
      - image: python:3.8
    steps:
      - checkout
      - run:
        name: Move into Week 1
        command: cd "Week_1"
      - run:
          name: Install dependencies
          command: pip3 install -r requirements.txt
      - run:
          name: Run tests
          command: pytest testsuite.py

workflows:
  version: 2
  build:
    jobs:
      - build
